security:
  oauth2:
    client:
      client-id: zxing2
      client-secret: zxingsecret2
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
server:
  port: 8060
  context-path: /client2